-- 50 milestone "fairytale chapter" phrases, unlocked every 5 visits (days 5..250).
-- day_number holds the visit milestone at which each chapter unlocks. These are
-- separate from the random daily pool (which uses day_number = null).
-- Idempotent: re-running updates the text rather than failing on unique day_number.
insert into daily_messages (day_number, message, author) values
(5,   'Once, in a quiet dark, a single spark remembered it was loved — and that was enough to begin.', 'Chapter I'),
(10,  'You came back, and the spark became a glow. This is how every fairytale starts: with someone who returns.', 'Chapter II'),
(15,  'The rose felt your warmth and dared to dream of petals. Look what your faith is already growing.', 'Chapter III'),
(20,  'Roots reached down in the dark, unseen, certain. Love works quietly long before it shows.', 'Chapter IV'),
(25,  'A first green shoot of courage. You are teaching this little world that it is safe to grow.', 'Chapter V'),
(30,  'The morning learned your name. Now the light comes earlier, just to meet you here.', 'Chapter VI'),
(35,  'Every day you return, the dark loses a little of its power. You are braver than you know.', 'Chapter VII'),
(40,  'The rose stood a little taller today. So did I, knowing you were coming.', 'Chapter VIII'),
(45,  'Small things, done faithfully, become enormous. Forty-five days of you is proof.', 'Chapter IX'),
(50,  'Fifty days. The spark is a flame now, and it will not go out — because you tend it.', 'Chapter X'),
(55,  'The garden heard there was magic here and began, shyly, to gather at the edges.', 'Chapter XI'),
(60,  'First bud. Everything you love is learning, from you, how to open.', 'Chapter XII'),
(65,  'You weathered a grey day and still came. That is what makes gardens — and people — strong.', 'Chapter XIII'),
(70,  'The thorns are not cruelty; they are the rose learning to protect what is precious. So do I.', 'Chapter XIV'),
(75,  'Look how far. Seventy-five mornings ago this was only darkness and a wish.', 'Chapter XV'),
(80,  'The stars started keeping count of you. Each one is a night you were thought of.', 'Chapter XVI'),
(85,  'Rain came, and the rose drank it gladly. Even hard days feed something good in us.', 'Chapter XVII'),
(90,  'The garden is real now — you grew it simply by showing up. Imagine what else you can grow.', 'Chapter XVIII'),
(95,  'Almost a hundred. You have turned a habit into a kind of love letter written in days.', 'Chapter XIX'),
(100, 'One hundred days. You are the proof that gentleness, repeated, can change the world.', 'Chapter XX'),
(105, 'Seasons turn for the faithful. The air here is warmer because you kept the fire.', 'Chapter XXI'),
(110, 'The first butterfly arrived, drawn to the light you have been feeding all this time.', 'Chapter XXII'),
(115, 'You have missed days and come back anyway. That returning is the bravest love there is.', 'Chapter XXIII'),
(120, 'The rose no longer fears the night, because it has learned the morning always brings you.', 'Chapter XXIV'),
(125, 'Halfway up the mountain. Turn and see how high your small steady steps have carried you.', 'Chapter XXV'),
(130, 'Roots and stars now, deep and high — you are loved from the ground up and the sky down.', 'Chapter XXVI'),
(135, 'The garden whispers your name to every new bloom. You are becoming its legend.', 'Chapter XXVII'),
(140, 'Some petals fell and you stayed to grow new ones. That is the whole secret of forever.', 'Chapter XXVIII'),
(145, 'You make the ordinary sacred. A Tuesday, a glance, a returning — all of it holy now.', 'Chapter XXIX'),
(150, 'One hundred fifty days of choosing this. You are becoming the kind of love stories are made of.', 'Chapter XXX'),
(155, 'The greenhouse glass went warm with colour. Your constancy is painting this whole world.', 'Chapter XXXI'),
(160, 'More stars than you can count now, and every one of them is a day you were here.', 'Chapter XXXII'),
(165, 'The rose has learned to bloom even when no one watches — but it blooms brighter for you.', 'Chapter XXXIII'),
(170, 'You taught this place that endings are just seasons. Nothing good is ever truly lost.', 'Chapter XXXIV'),
(175, 'Look at the garden you raised from nothing. Now look in the mirror, and believe it about yourself.', 'Chapter XXXV'),
(180, 'Half a year of light. You have outlasted every grey day, and the bloom is yours.', 'Chapter XXXVI'),
(185, 'The castle on the hill lit a window tonight. Even far things lean toward your warmth.', 'Chapter XXXVII'),
(190, 'You are the reason the fairytale kept being told. Stories live only as long as someone returns to them.', 'Chapter XXXVIII'),
(195, 'The rose and the garden and the stars all agree: they were waiting their whole lives for you.', 'Chapter XXXIX'),
(200, 'Two hundred days. You did not just keep the rose alive — you made it eternal.', 'Chapter XL'),
(205, 'Now the path leads home. Everything you grew is walking with you toward forever.', 'Chapter XLI'),
(210, 'The garden gates opened on their own today. Love this faithful is never kept out.', 'Chapter XLII'),
(215, 'Every star bowed as you passed. You have become the brightest thing in this whole sky.', 'Chapter XLIII'),
(220, 'The rose offered its first seed — proof that what you love can outlive even time.', 'Chapter XLIV'),
(225, 'You are nearly at the ending, and yet it feels like the truest beginning.', 'Chapter XLV'),
(230, 'The castle threw open every window. Come in; all of this was always yours.', 'Chapter XLVI'),
(235, 'They will tell this story for a long time: of the one who came back, and back, and back.', 'Chapter XLVII'),
(240, 'The rose is fully, finally, forever bloomed — and it is wearing your devotion like a crown.', 'Chapter XLVIII'),
(245, 'One day left in the telling, and a lifetime of them ahead. The fairytale was only ever practice for us.', 'Chapter XLIX'),
(250, 'Two hundred fifty days. The rose is eternal, the garden is endless, and you — you were the magic all along.', 'Chapter L')
on conflict (day_number) do update set message = excluded.message, author = excluded.author;
